import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: "en", name: "English", native: "English", flag: "🇬🇧", region: "International" },
  { code: "hi", name: "Hindi", native: "हिन्दी", flag: "🇮🇳", region: "National" },
  { code: "mr", name: "Marathi", native: "मराठी", flag: "🇮🇳", region: "Maharashtra" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", flag: "🇮🇳", region: "Gujarat" },
  { code: "ta", name: "Tamil", native: "தமிழ்", flag: "🇮🇳", region: "Tamil Nadu" },
  { code: "te", name: "Telugu", native: "తెలుగు", flag: "🇮🇳", region: "Andhra / Telangana" },
  { code: "bn", name: "Bengali", native: "বাংলা", flag: "🇮🇳", region: "West Bengal" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", flag: "🇮🇳", region: "Karnataka" },
  { code: "ml", name: "Malayalam", native: "മലയാളം", flag: "🇮🇳", region: "Kerala" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ", flag: "🇮🇳", region: "Punjab" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ", flag: "🇮🇳", region: "Odisha" },
  { code: "ur", name: "Urdu", native: "اردو", flag: "🇮🇳", region: "National" },
  { code: "as", name: "Assamese", native: "অসমীয়া", flag: "🇮🇳", region: "Assam" },
];

export const TRANSLATIONS = {
  en: {
    // Nav & Common
    findParking: "Find Parking",
    myBookings: "My Bookings",
    myVehicles: "My Vehicles",
    dashboard: "Dashboard",
    addFacility: "Add Facility",
    scanPass: "Scan Pass",
    commandCenter: "Command Center",
    profileSettings: "Profile & Settings",
    signOut: "Sign Out",
    theme: "Theme",
    language: "Language",
    notifications: "Notifications",
    systemOnline: "System Online",
    realtimeSync: "Real-time slot sync is active.",
    searchPlaceholder: "Search by city, area, landmark...",
    filterAll: "All",
    filterAvailable: "Available",
    filterEV: "EV Charging",
    filterDaily: "Daily Pass",
    filterFree: "Free",
    availableSlots: "Available Slots",
    hourlyRate: "Hourly Rate",
    dailyRate: "Daily Pass",
    bookNow: "Book Now",
    viewDetails: "View Details",
    activeBookings: "Active Bookings",
    totalFacilities: "Total Facilities",
    totalRevenue: "Total Revenue",
    occupancyRate: "Occupancy Rate",
    liveOperations: "Live Operations",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    status: "Status",
    actions: "Actions",
    confirm: "Confirm",
    cancel: "Cancel",
    save: "Save Changes",
    loading: "Loading...",
    noDataFound: "No data found",
    appearance: "Appearance & Theme",
    selectLanguage: "Select Indian Language",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    midnightMode: "Midnight Mode",
    systemMode: "System Mode",
  },
  hi: {
    findParking: "पार्किंग खोजें",
    myBookings: "मेरी बुकिंग",
    myVehicles: "मेरे वाहन",
    dashboard: "डैशबोर्ड",
    addFacility: "पार्किंग जोड़ें",
    scanPass: "पास स्कैन करें",
    commandCenter: "कमांड सेंटर",
    profileSettings: "प्रोफ़ाइल और सेटिंग्स",
    signOut: "साइन आउट",
    theme: "थीम मोड",
    language: "भाषा",
    notifications: "सूचनाएं",
    systemOnline: "सिस्टम ऑनलाइन है",
    realtimeSync: "रीयल-टाइम स्लॉट सिंक सक्रिय है।",
    searchPlaceholder: "शहर, क्षेत्र, लैंडमार्क खोजें...",
    filterAll: "सभी",
    filterAvailable: "उपलब्ध",
    filterEV: "ईवी चार्जिंग",
    filterDaily: "दैनिक पास",
    filterFree: "निःशुल्क",
    availableSlots: "उपलब्ध स्लॉट",
    hourlyRate: "प्रति घंटा दर",
    dailyRate: "दैनिक पास",
    bookNow: "अभी बुक करें",
    viewDetails: "विवरण देखें",
    activeBookings: "सक्रिय बुकिंग",
    totalFacilities: "कुल पार्किंग स्थल",
    totalRevenue: "कुल आय",
    occupancyRate: "ऑक्यूपेंसी दर",
    liveOperations: "लाइव संचालन",
    approved: "स्वीकृत",
    pending: "लंबित",
    rejected: "अस्वीकृत",
    status: "स्थिति",
    actions: "कार्रवाई",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    save: "बदलाव सहेजें",
    loading: "लोड हो रहा है...",
    noDataFound: "कोई डेटा नहीं मिला",
    appearance: "दिखावट और थीम",
    selectLanguage: "भारतीय भाषा चुनें",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    midnightMode: "मिडनाइट मोड",
    systemMode: "सिस्टम मोड",
  },
  mr: {
    findParking: "पार्किंग शोधा",
    myBookings: "माझी बुकिंग्ज",
    myVehicles: "माझी वाहने",
    dashboard: "डॅशबोर्ड",
    addFacility: "पार्किंग जोडा",
    scanPass: "पास स्कॅन करा",
    commandCenter: "कमांड सेंटर",
    profileSettings: "प्रोफाइल आणि सेटिंग्ज",
    signOut: "साइन आउट",
    theme: "थीम मोड",
    language: "भाषा",
    notifications: "सूचना",
    systemOnline: "प्रणाली ऑनलाइन आहे",
    realtimeSync: "रिअल-टाइम स्लॉट सिंक सुरू आहे.",
    searchPlaceholder: "शहर, परिसर किंवा ठिकाण शोधा...",
    filterAll: "सर्व",
    filterAvailable: "उपलब्ध",
    filterEV: "ईव्ही चार्जिंग",
    filterDaily: "दैनिक पास",
    filterFree: "मोफत",
    availableSlots: "उपलब्ध स्लॉट",
    hourlyRate: "तासाचा दर",
    dailyRate: "दैनिक पास",
    bookNow: "आत्ताच बुक करा",
    viewDetails: "तपशील पहा",
    activeBookings: "सक्रिय बुकिंग",
    totalFacilities: "एकूण सुविधा",
    totalRevenue: "एकूण कमाई",
    occupancyRate: "ऑक्युपन्सी दर",
    liveOperations: "थेट ऑपरेशन्स",
    approved: "मंजूर",
    pending: "प्रलंबित",
    rejected: "नाकारले",
    status: "स्थिती",
    actions: "कृती",
    confirm: "पुष्टी करा",
    cancel: "रद्द करा",
    save: "बदल जतन करा",
    loading: "लोड होत आहे...",
    noDataFound: "कोणतीही माहिती आढळली नाही",
    appearance: "दिसणे आणि थीम",
    selectLanguage: "भारतीय भाषा निवडा",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    midnightMode: "मिडनाइट मोड",
    systemMode: "सिस्टम मोड",
  },
  gu: {
    findParking: "પાર્કિંગ શોધો",
    myBookings: "મારી બુકિંગ",
    myVehicles: "મારા વાહનો",
    dashboard: "ડેશબોર્ડ",
    addFacility: "પાર્કિંગ ઉમેરો",
    scanPass: "પાસ સ્કેન કરો",
    commandCenter: "કમાન્ડ સેન્ટર",
    profileSettings: "પ્રોફાઇલ અને સેટિંગ્સ",
    signOut: "સાઇન આઉટ",
    theme: "થીમ મોડ",
    language: "ભાષા",
    notifications: "સૂચનાઓ",
    systemOnline: "સિસ્ટમ ઓનલાઈન છે",
    realtimeSync: "રીઅલ-ટાઇમ સ્લોટ સિંક સક્રિય છે.",
    searchPlaceholder: "શહેર, વિસ્તાર, લેન્ડમાર્ક શોધો...",
    filterAll: "બધા",
    filterAvailable: "ઉપલબ્ધ",
    filterEV: "ઇવી ચાર્જિંગ",
    filterDaily: "દૈનિક પાસ",
    filterFree: "મફત",
    availableSlots: "ઉપલબ્ધ સ્લોટ",
    hourlyRate: "કલાક દીઠ દર",
    dailyRate: "દૈનિક પાસ",
    bookNow: "હમણાં બુક કરો",
    viewDetails: "વિગતો જુઓ",
    activeBookings: "સક્રિય બુકિંગ",
    totalFacilities: "કુલ સુવિધાઓ",
    totalRevenue: "કુલ આવક",
    occupancyRate: "ઓક્યુપન્સી દર",
    liveOperations: "લાઈવ કામગીરી",
    approved: "મંજૂર",
    pending: "બાકી",
    rejected: "અસ્વીકાર",
    status: "સ્થિતિ",
    actions: "ક્રિયાઓ",
    confirm: "પુષ્ટિ કરો",
    cancel: "રદ કરો",
    save: "ફેરફારો સાચવો",
    loading: "લોડ થઈ રહ્યું છે...",
    noDataFound: "કોઈ ડેટા મળ્યો નથી",
    appearance: "દેખાવ અને થીમ",
    selectLanguage: "ભારતીય ભાષા પસંદ કરો",
    lightMode: "લાઇટ મોડ",
    darkMode: "ડાર્ક મોડ",
    midnightMode: "મિડનાઇટ મોડ",
    systemMode: "સિસ્ટમ મોડ",
  },
  ta: {
    findParking: "பார்க்கிங் தேடுங்கள்",
    myBookings: "என் முன்பதிவுகள்",
    myVehicles: "என் வாகனங்கள்",
    dashboard: "டாஷ்போர்டு",
    addFacility: "பார்க்கிங் சேர்",
    scanPass: "பாஸ் ஸ்கேன் செய்",
    commandCenter: "கட்டளை மையம்",
    profileSettings: "சுயவிவரம் & அமைப்புகள்",
    signOut: "வெளியேறு",
    theme: "தீம் முறை",
    language: "மொழி",
    notifications: "அறிவிப்புகள்",
    systemOnline: "அமைப்பு ஆன்லைனில் உள்ளது",
    realtimeSync: "நேரடி இட ஒத்திசைவு செயலில் உள்ளது.",
    searchPlaceholder: "நகரம், பகுதி, அடையாளம் தேடுங்கள்...",
    filterAll: "அனைத்தும்",
    filterAvailable: "கிடைக்கும்",
    filterEV: "EV சார்ஜிங்",
    filterDaily: "தினசரி பாஸ்",
    filterFree: "இலவசம்",
    availableSlots: "கிடைக்கும் இடங்கள்",
    hourlyRate: "மணிநேர கட்டணம்",
    dailyRate: "தினசரி பாஸ்",
    bookNow: "இப்போது பதிவு செய்",
    viewDetails: "விவரங்களை காண்க",
    activeBookings: "செயலில் உள்ள முன்பதிவுகள்",
    totalFacilities: "மொத்த பார்க்கிங் மையங்கள்",
    totalRevenue: "மொத்த வருவாய்",
    occupancyRate: "ஆக்கிரமிப்பு விகிதம்",
    liveOperations: "நேரடி செயல்பாடுகள்",
    approved: "அங்கீகரிக்கப்பட்டது",
    pending: "நிலுவையில் உள்ளது",
    rejected: "நிராகரிக்கப்பட்டது",
    status: "நிலை",
    actions: "செயல்கள்",
    confirm: "உறுதி செய்",
    cancel: "ரத்து செய்",
    save: "மாற்றங்களைச் சேமி",
    loading: "ஏற்றுகிறது...",
    noDataFound: "தரவு எதுவும் கிடைக்கவில்லை",
    appearance: "தோற்றம் & தீம்",
    selectLanguage: "இந்திய மொழியைத் தேர்ந்தெடுக்கவும்",
    lightMode: "லைட் பயன்முறை",
    darkMode: "டார்க் பயன்முறை",
    midnightMode: "மிட்நைட் பயன்முறை",
    systemMode: "சிஸ்டம் பயன்முறை",
  },
  te: {
    findParking: "పార్కింగ్ కనుగొనండి",
    myBookings: "నా బుకింగ్స్",
    myVehicles: "నా వాహనాలు",
    dashboard: "డాష్‌బోర్డ్",
    addFacility: "పార్కింగ్ జోడించండి",
    scanPass: "పాస్ స్కాన్ చేయండి",
    commandCenter: "కమాండ్ సెంటర్",
    profileSettings: "ప్రొఫైల్ & సెట్టింగ్‌లు",
    signOut: "లాగ్ అవుట్",
    theme: "థీమ్ మోడ్",
    language: "భాష",
    notifications: "నోటిఫికేషన్‌లు",
    systemOnline: "సిస్టమ్ ఆన్‌లైన్‌లో ఉంది",
    realtimeSync: "రియల్-టైమ్ స్లాట్ సింక్ సక్రియంగా ఉంది.",
    searchPlaceholder: "నగరం, ప్రాంతం, ల్యాండ్‌మార్క్ వెతకండి...",
    filterAll: "అన్నీ",
    filterAvailable: "అందుబాటులో ఉన్నాయి",
    filterEV: "EV ఛార్జింగ్",
    filterDaily: "రోజువారీ పాస్",
    filterFree: "ఉచితం",
    availableSlots: "అందుబాటులో ఉన్న స్లాట్‌లు",
    hourlyRate: "గంట రేటు",
    dailyRate: "రోజువారీ పాస్",
    bookNow: "ఇప్పుడే బుక్ చేయండి",
    viewDetails: "వివరాలు చూడండి",
    activeBookings: "క్రియాశీల బుకింగ్స్",
    totalFacilities: "మొత్తం పార్కింగ్ సదుపాయాలు",
    totalRevenue: "మొత్తం ఆదాయం",
    occupancyRate: "ఆక్యుపెన్సీ రేటు",
    liveOperations: "లైవ్ కార్యకలాపాలు",
    approved: "ఆమోదించబడింది",
    pending: "పెండింగ్‌లో ఉంది",
    rejected: "తిరస్కరించబడింది",
    status: "స్థితి",
    actions: "చర్యలు",
    confirm: "నిర్ధారించండి",
    cancel: "రద్దు చేయండి",
    save: "మార్పులను సేవ్ చేయండి",
    loading: "లోడ్ అవుతోంది...",
    noDataFound: "డేటా కనుగొనబడలేదు",
    appearance: "రూపం & థీమ్",
    selectLanguage: "భారతీయ భాషను ఎంచుకోండి",
    lightMode: "లైట్ మోడ్",
    darkMode: "డార్క్ మోడ్",
    midnightMode: "మిడ్‌నైట్ మోడ్",
    systemMode: "సిస్టమ్ మోడ్",
  },
  bn: {
    findParking: "পার্কিং খুঁজুন",
    myBookings: "আমার বুকিং",
    myVehicles: "আমার যানবাহন",
    dashboard: "ড্যাশবোর্ড",
    addFacility: "পার্কিং যোগ করুন",
    scanPass: "পাস স্ক্যান করুন",
    commandCenter: "কমান্ড সেন্টার",
    profileSettings: "প্রোফাইল এবং সেটিংস",
    signOut: "সাইন আউট",
    theme: "থিম মোড",
    language: "ভাষা",
    notifications: "বিজ্ঞপ্তি",
    systemOnline: "সিস্টেম অনলাইন আছে",
    realtimeSync: "রিয়েল-টাইম স্লট সিঙ্ক সক্রিয়।",
    searchPlaceholder: "শহর, এলাকা, ল্যান্ডমার্ক অনুসন্ধান করুন...",
    filterAll: "সব",
    filterAvailable: "উপলব্ধ",
    filterEV: "ইভি চার্জিং",
    filterDaily: "দৈনিক পাস",
    filterFree: "বিনামূল্যে",
    availableSlots: "উপলব্ধ স্লট",
    hourlyRate: "ঘণ্টাপ্রতি হার",
    dailyRate: "দৈনিক পাস",
    bookNow: "এখনই বুক করুন",
    viewDetails: "বিস্তারিত দেখুন",
    activeBookings: "সক্রিয় বুকিং",
    totalFacilities: "মোট পার্কিং সুবিধা",
    totalRevenue: "মোট আয়",
    occupancyRate: "অকুপেন্সি হার",
    liveOperations: "লাইভ অপারেশন",
    approved: "অনুমোদিত",
    pending: "অপেক্ষারত",
    rejected: "প্রত্যাখ্যাত",
    status: "অবস্থা",
    actions: "পদক্ষেপ",
    confirm: "নিশ্চিত করুন",
    cancel: "বাতিল করুন",
    save: "পরিবর্তন সংরক্ষণ করুন",
    loading: "লোড হচ্ছে...",
    noDataFound: "কোন তথ্য পাওয়া যায়নি",
    appearance: "চেহারা এবং থিম",
    selectLanguage: "ভারতীয় ভাষা নির্বাচন করুন",
    lightMode: "লাইট মোড",
    darkMode: "ডার্ক মোড",
    midnightMode: "মিডনাইট মোড",
    systemMode: "সিস্টেম মোড",
  },
  kn: {
    findParking: "ಪಾರ್ಕಿಂಗ್ ಹುಡುಕಿ",
    myBookings: "ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು",
    myVehicles: "ನನ್ನ ವಾಹನಗಳು",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    addFacility: "ಪಾರ್ಕಿಂಗ್ ಸೇರಿಸಿ",
    scanPass: "ಪಾಸ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    commandCenter: "ಕಮಾಂಡ್ ಸೆಂಟರ್",
    profileSettings: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    signOut: "ಸೈನ್ ಔಟ್",
    theme: "ಥೀಮ್ ಮೋಡ್",
    language: "ಭಾಷೆ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    systemOnline: "ವ್ಯವಸ್ಥೆ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿದೆ",
    realtimeSync: "ರಿಯಲ್-ಟೈಮ್ ಸ್ಲಾಟ್ ಸಿಂಕ್ ಸಕ್ರಿಯವಾಗಿದೆ.",
    searchPlaceholder: "ನಗರ, ಪ್ರದೇಶ, ಸ್ಥಳ ಹುಡುಕಿ...",
    filterAll: "ಎಲ್ಲವೂ",
    filterAvailable: "ಲಭ್ಯವಿದೆ",
    filterEV: "ಇವಿ ಚಾರ್ಜಿಂಗ್",
    filterDaily: "ದೈನಂದಿನ ಪಾಸ್",
    filterFree: "ಉಚಿತ",
    availableSlots: "ಲಭ್ಯವಿರುವ ಸ್ಲಾಟ್‌ಗಳು",
    hourlyRate: "ಗಂಟೆಯ ದರ",
    dailyRate: "ದೈನಂದಿನ ಪಾಸ್",
    bookNow: "ಈಗಲೇ ಬುಕ್ ಮಾಡಿ",
    viewDetails: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    activeBookings: "ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು",
    totalFacilities: "ಒಟ್ಟು ಸೌಲಭ್ಯಗಳು",
    totalRevenue: "ಒಟ್ಟು ಆದಾಯ",
    occupancyRate: "ಆಕ್ಯುಪೆನ್ಸಿ ದರ",
    liveOperations: "ಲೈವ್ ಕಾರ್ಯಾಚರಣೆಗಳು",
    approved: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
    pending: "ಬಾಕಿ ಉಳಿದಿದೆ",
    rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
    status: "ಸ್ಥಿತಿ",
    actions: "ಕ್ರಮಗಳು",
    confirm: "ದೃಢೀಕರಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    save: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    noDataFound: "ಯಾವುದೇ ಡೇಟಾ ಕಂಡುಬಂದಿಲ್ಲ",
    appearance: "ಗೋಚರತೆ ಮತ್ತು ಥೀಮ್",
    selectLanguage: "ಭಾರತೀಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    lightMode: "ಲೈಟ್ ಮೋಡ್",
    darkMode: "ಡಾರ್ಕ್ ಮೋಡ್",
    midnightMode: "ಮಿಡ್‌ನೈಟ್ ಮೋಡ್",
    systemMode: "ಸಿಸ್ಟಮ್ ಮೋಡ್",
  },
  ml: {
    findParking: "പാർക്കിംഗ് കണ്ടെത്തുക",
    myBookings: "എന്റെ ബുക്കിംഗുകൾ",
    myVehicles: "എന്റെ വാഹനങ്ങൾ",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    addFacility: "പാർക്കിംഗ് ചേർക്കുക",
    scanPass: "പാസ് സ്കാൻ ചെയ്യുക",
    commandCenter: "കമാൻഡ് സെന്റർ",
    profileSettings: "പ്രൊഫൈലും ക്രമീകരണങ്ങളും",
    signOut: "സൈൻ ഔട്ട്",
    theme: "തീം മോഡ്",
    language: "ഭാഷ",
    notifications: "അറിയിപ്പുകൾ",
    systemOnline: "സിസ്റ്റം ഓൺലൈനിലാണ്",
    realtimeSync: "തത്സമയ സ്ലോട്ട് സമന്വയം സജീവമാണ്.",
    searchPlaceholder: "നഗരം, പ്രദേശം, സ്ഥലം തിരയുക...",
    filterAll: "എല്ലാം",
    filterAvailable: "ലഭ്യമാണ്",
    filterEV: "ഇവി ചാർജിംഗ്",
    filterDaily: "പ്രതിദിന പാസ്",
    filterFree: "സൗജന്യം",
    availableSlots: "ലഭ്യമായ സ്ലോട്ടുകൾ",
    hourlyRate: "മണിക്കൂർ നിരക്ക്",
    dailyRate: "പ്രതിദിന പാസ്",
    bookNow: "ഇപ്പോൾ ബുക്ക് ചെയ്യുക",
    viewDetails: "വിശദാംശങ്ങൾ കാണുക",
    activeBookings: "സജീവ ബുക്കിംഗുകൾ",
    totalFacilities: "ആകെ പാർക്കിംഗ് കേന്ദ്രങ്ങൾ",
    totalRevenue: "ആകെ വരുമാനം",
    occupancyRate: "ഒക്യുപ്പൻസി നിരക്ക്",
    liveOperations: "തത്സമയ പ്രവർത്തനങ്ങൾ",
    approved: "അംഗീകരിച്ചു",
    pending: "തീർപ്പുകൽപ്പിക്കാത്തത്",
    rejected: "നിരസിച്ചു",
    status: "നില",
    actions: "പ്രവർത്തനങ്ങൾ",
    confirm: "സ്ഥിരീകരിക്കുക",
    cancel: "റദ്ദാക്കുക",
    save: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
    loading: "ലോഡുചെയ്യുന്നു...",
    noDataFound: "വിവരങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
    appearance: "രൂപവും തീമും",
    selectLanguage: "ഇന്ത്യൻ ഭാഷ തിരഞ്ഞെടുക്കുക",
    lightMode: "ലൈറ്റ് മോഡ്",
    darkMode: "ഡാർക്ക് മോഡ്",
    midnightMode: "മിഡ്‌നൈറ്റ് മോഡ്",
    systemMode: "സിസ്റ്റം മോഡ്",
  },
  pa: {
    findParking: "ਪਾਰਕਿੰਗ ਲੱਭੋ",
    myBookings: "ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ",
    myVehicles: "ਮੇਰੇ ਵਾਹਨ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    addFacility: "ਪਾਰਕਿੰਗ ਸ਼ਾਮਲ ਕਰੋ",
    scanPass: "ਪਾਸ ਸਕੈਨ ਕਰੋ",
    commandCenter: "ਕਮਾਂਡ ਸੈਂਟਰ",
    profileSettings: "ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਸੈਟਿੰਗਾਂ",
    signOut: "ਸਾਈਨ ਆਉਟ",
    theme: "ਥੀਮ ਮੋਡ",
    language: "ਭਾਸ਼ਾ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    systemOnline: "ਸਿਸਟਮ ਔਨਲਾਈਨ ਹੈ",
    realtimeSync: "ਰੀਅਲ-ਟਾਈਮ ਸਲਾਟ ਸਿੰਕ ਸਰਗਰਮ ਹੈ।",
    searchPlaceholder: "ਸ਼ਹਿਰ, ਖੇਤਰ ਜਾਂ ਸਥਾਨ ਖੋਜੋ...",
    filterAll: "ਸਾਰੇ",
    filterAvailable: "ਉਪਲਬਧ",
    filterEV: "ਈਵੀ ਚਾਰਜਿੰਗ",
    filterDaily: "ਰੋਜ਼ਾਨਾ ਪਾਸ",
    filterFree: "ਮੁਫ਼ਤ",
    availableSlots: "ਉਪਲਬਧ ਸਲਾਟ",
    hourlyRate: "ਪ੍ਰਤੀ ਘੰਟਾ ਦਰ",
    dailyRate: "ਰੋਜ਼ਾਨਾ ਪਾਸ",
    bookNow: "ਹੁਣੇ ਬੁੱਕ ਕਰੋ",
    viewDetails: "ਵੇਰਵੇ ਦੇਖੋ",
    activeBookings: "ਸਰਗਰਮ ਬੁਕਿੰਗਾਂ",
    totalFacilities: "ਕੁੱਲ ਪਾਰਕਿੰਗ ਸਹੂਲਤਾਂ",
    totalRevenue: "ਕੁੱਲ ਕਮਾਈ",
    occupancyRate: "ਆਕੂਪੈਂਸੀ ਦਰ",
    liveOperations: "ਲਾਈਵ ਸੰਚਾਲਨ",
    approved: "ਪ੍ਰਵਾਨਿਤ",
    pending: "ਬਕਾਇਆ",
    rejected: "ਰੱਦ",
    status: "ਸਥਿਤੀ",
    actions: "ਕਾਰਵਾਈਆਂ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    save: "ਬਦਲਾਅ ਸੰਭਾਲੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    noDataFound: "ਕੋਈ ਡਾਟਾ ਨਹੀਂ ਮਿਲਿਆ",
    appearance: "ਦਿੱਖ ਅਤੇ ਥੀਮ",
    selectLanguage: "ਭਾਰਤੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    lightMode: "ਲਾਈਟ ਮੋਡ",
    darkMode: "ਡਾਰਕ ਮੋਡ",
    midnightMode: "ਮਿਡਨਾਈਟ ਮੋਡ",
    systemMode: "ਸਿਸਟਮ ਮੋਡ",
  },
  or: {
    findParking: "ପାର୍କିଂ ଖୋଜନ୍ତୁ",
    myBookings: "ମୋର ବୁକିଂ",
    myVehicles: "ମୋର ଗାଡ଼ି",
    dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    addFacility: "ପାର୍କିଂ ଯୋଡନ୍ତୁ",
    scanPass: "ପାସ ସ୍କାନ କରନ୍ତୁ",
    commandCenter: "କମାଣ୍ଡ ସେଣ୍ଟର",
    profileSettings: "ପ୍ରୋଫାଇଲ ଏବଂ ସେଟିଂସ",
    signOut: "ସାଇନ ଆଉଟ",
    theme: "ଥିମ ମୋଡ",
    language: "ଭାଷା",
    notifications: "ବିଜ୍ଞପ୍ତି",
    systemOnline: "ସିଷ୍ଟମ ଅନଲାଇନ ଅଛି",
    realtimeSync: "ରିଅଲ-ଟାଇମ ସ୍ଲଟ ସିଙ୍କ ସକ୍ରିୟ ଅଛି।",
    searchPlaceholder: "ସହର, ଅଞ୍ଚଳ ଖୋଜନ୍ତୁ...",
    filterAll: "ସମସ୍ତ",
    filterAvailable: "ଉପଲବ୍ଧ",
    filterEV: "ଇଭି ଚାର୍ଜିଂ",
    filterDaily: "ଦୈନିକ ପାସ",
    filterFree: "ମାଗଣା",
    availableSlots: "ଉପଲବ୍ଧ ସ୍ଲଟ",
    hourlyRate: "ଘଣ୍ଟା ପ୍ରତି ଦର",
    dailyRate: "ଦୈନିକ ପାସ",
    bookNow: "ବର୍ତ୍ତମାନ ବୁକ କରନ୍ତୁ",
    viewDetails: "ବିବରଣୀ ଦେଖନ୍ତୁ",
    activeBookings: "ସକ୍ରିୟ ବୁକିଂ",
    totalFacilities: "ମୋଟ ପାର୍କିଂ ସୁବିଧା",
    totalRevenue: "ମୋଟ ଆୟ",
    occupancyRate: "ଅଧିକୃତ ହାର",
    liveOperations: "ଲାଇଭ ଅପରେସନ",
    approved: "ଅନୁମୋଦିତ",
    pending: "ବକେୟା",
    rejected: "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    status: "ସ୍ଥିତି",
    actions: "କାର୍ଯ୍ୟାନୁଷ୍ଠାନ",
    confirm: "ନିଶ୍ଚିତ କରନ୍ତୁ",
    cancel: "ବାତିଲ କରନ୍ତୁ",
    save: "ପରିବର୍ତ୍ତନ ସଂରକ୍ଷଣ କରନ୍ତୁ",
    loading: "ଲୋଡ ହେଉଛି...",
    noDataFound: "କୌଣସି ତଥ୍ୟ ମିଳିଲା ନାହିଁ",
    appearance: "ରୂପ ଏବଂ ଥିମ",
    selectLanguage: "ଭାରତୀୟ ଭାଷା ଚୟନ କରନ୍ତୁ",
    lightMode: "ଲାଇଟ ମୋଡ",
    darkMode: "ଡାର୍କ ମୋଡ",
    midnightMode: "ମିଡନାଇଟ ମୋଡ",
    systemMode: "ସିଷ୍ଟମ ମୋଡ",
  },
  ur: {
    findParking: "پارکنگ تلاش کریں",
    myBookings: "میری بکنگز",
    myVehicles: "میری گاڑیاں",
    dashboard: "ڈیش بورڈ",
    addFacility: "پارکنگ شامل کریں",
    scanPass: "پاس اسکین کریں",
    commandCenter: "کمانڈ سینٹر",
    profileSettings: "پروفائل اور ترتیبات",
    signOut: "سائن آؤٹ",
    theme: "تھیم موڈ",
    language: "زبان",
    notifications: "اطلاعات",
    systemOnline: "سسٹم آن لائن ہے",
    realtimeSync: "ریئل ٹائم سلاٹ کی مطابقت پذیری فعال ہے۔",
    searchPlaceholder: "شہر، علاقہ، نشان تلاش کریں...",
    filterAll: "تمام",
    filterAvailable: "دستیاب",
    filterEV: "ای وی چارجنگ",
    filterDaily: "روزانہ پاس",
    filterFree: "مفت",
    availableSlots: "دستیاب سلاٹس",
    hourlyRate: "فی گھنٹہ کی شرح",
    dailyRate: "روزانہ پاس",
    bookNow: "ابھی بک کریں",
    viewDetails: "تفصیلات دیکھیں",
    activeBookings: "فعال بکنگز",
    totalFacilities: "کل پارکنگ سہولیات",
    totalRevenue: "کل آمدنی",
    occupancyRate: "شرح قبضگی",
    liveOperations: "براہ راست آپریشنز",
    approved: "منظور شدہ",
    pending: "زیر التواء",
    rejected: "مسترد",
    status: "حیثیت",
    actions: "اقدامات",
    confirm: "تصدیق کریں",
    cancel: "منسوخ کریں",
    save: "تبدیلیاں محفوظ کریں",
    loading: "لوڈ ہو رہا ہے...",
    noDataFound: "کوئی ڈیٹا نہیں ملا",
    appearance: "ظاہری شکل اور تھیم",
    selectLanguage: "ہندوستانی زبان منتخب کریں",
    lightMode: "لائٹ موڈ",
    darkMode: "ڈارک موڈ",
    midnightMode: "مڈ نائٹ موڈ",
    systemMode: "سسٹم موڈ",
  },
  as: {
    findParking: "পাৰ্কিং বিচাৰক",
    myBookings: "মোৰ বুকিং",
    myVehicles: "মোৰ বাহনসমূহ",
    dashboard: "ডেশ্ববৰ্ড",
    addFacility: "পাৰ্কিং যোগ কৰক",
    scanPass: "পাছ স্কেন কৰক",
    commandCenter: "কমাণ্ড চেণ্টাৰ",
    profileSettings: "প্ৰফাইল আৰু ছেটিংছ",
    signOut: "ছাইন আউট",
    theme: "থিম মোড",
    language: "ভাষা",
    notifications: "জাননীসমূহ",
    systemOnline: "ছিষ্টেম অনলাইন আছে",
    realtimeSync: "ৰিয়েল-টাইম স্লট চিংক সক্ৰিয়।",
    searchPlaceholder: "চহৰ, অঞ্চল বা স্থান সন্ধান কৰক...",
    filterAll: "সকলো",
    filterAvailable: "উপলব্ধ",
    filterEV: "ইভি চাৰ্জিং",
    filterDaily: "দৈনিক পাছ",
    filterFree: "বিনামূলীয়া",
    availableSlots: "উপলব্ধ স্লট",
    hourlyRate: "ঘণ্টাৰ হাৰ",
    dailyRate: "দৈনিক পাছ",
    bookNow: "এতিয়াই বুক কৰক",
    viewDetails: "বিৱৰণ চাওক",
    activeBookings: "সক্ৰিয় বুকিং",
    totalFacilities: "মুঠ পাৰ্কিং সুবিধা",
    totalRevenue: "মুঠ উপাৰ্জন",
    occupancyRate: "অকুপেনচি হাৰ",
    liveOperations: "লাইভ কাৰ্যকলাপ",
    approved: "অনুমোদিত",
    pending: "বাকী থকা",
    rejected: "প্ৰত্যাখ্যান কৰা হৈছে",
    status: "স্থিতি",
    actions: "কাৰ্য্য",
    confirm: "নিশ্চিত কৰক",
    cancel: "বাতিল কৰক",
    save: "পৰিৱৰ্তন সংৰক্ষণ কৰক",
    loading: "লোড হৈ আছে...",
    noDataFound: "কোনো তথ্য পোৱা নগ'ল",
    appearance: "ৰূপ আৰু থিম",
    selectLanguage: "ভাৰতীয় ভাষা বাছক",
    lightMode: "লাইট মোড",
    darkMode: "ডাৰ্ক মোড",
    midnightMode: "মিডনাইট মোড",
    systemMode: "ছিষ্টেম মোড",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const saved = localStorage.getItem("parkease_lang");
      if (saved && TRANSLATIONS[saved]) {
        return saved;
      }
    } catch {
      // ignore
    }
    return "en";
  });

  useEffect(() => {
    try {
      localStorage.setItem("parkease_lang", language);
    } catch {
      // ignore
    }
  }, [language]);

  const setLanguage = (code) => {
    if (TRANSLATIONS[code]) {
      setLanguageState(code);
    }
  };

  const t = (key, fallbackText) => {
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (currentDict && currentDict[key]) {
      return currentDict[key];
    }
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return fallbackText || key;
  };

  const currentLangObj = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        LANGUAGES,
        currentLanguage: currentLangObj,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
